apiVersion: v1
name: wavefront
description: Wavefront Kubernetes collector
appVersion: 1.0.9
version: 1.1.8
keywords:
- metric
- monitoring
- observability
- alerting
home: https://www.wavefront.com
sources:
- https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes
- https://github.com/wavefrontHQ/wavefront-proxy
maintainers:
- name: vikramraman
  email: rvikram@vmware.com
